spring.application.name=user-service

# connect with config server (import the config from config server)
# optional means if config server is down, it will get the properties from its own file.
spring.config.import=optional:configserver:http://config-server:8888

# Creating a separate file for docker properties because we need to override the properties for docker environment.
# We are referring to localhost in application.properties and localhost will not work in docker environment. So
# we are using service name instead of localhost and for that reason creating a separate docker properties file.
# As all the services will be running in the same docker network, we can use the service name to connect to each other.


