version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql:8
    mem_limit: 700m
    environment:
      MYSQL_ROOT_PASSWORD: falcon123
      MYSQL_DATABASE: ecomdb
    volumes:
      - mysql:/var/lib/mysql
      - ./init-multi-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - backend
    restart: unless-stopped

  adminer:
    container_name: adminer_container
    image: adminer
    mem_limit: 300m
    ports:
      - "8088:8080"
    networks:
      - backend
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASSWORD: guest
    ports:
      - "5672:5672"
      - "15672:15672" # RabbitMQ management UI (http://localhost:15672)
    networks:
      - backend
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - backend

# build means to build the image from the Dockerfile, dockerfile is present inside the configserver directory
  config-server:
    build: ./configserver
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - backend
    # mount the config folder from the host to the container at /config location. So it will first go to the
    # ./ means the current directory where our docker-compose.yml is present then from there it will go to the
    # configserver directory then inside the configserver directory it will go to the src/main/resources/config
    # then mount the config folder from the host to the container at /config location.
    volumes:
      - ./configserver/src/main/resources/config:/config

networks:
  backend:
    driver: bridge

volumes:
  mysql: