spring.application.name=product-service

# connect with config server (import the config from config server)
# optional means if config server is down, it will get the properties from its own file.
spring.config.import=optional:configserver:http://config-server:8888
