spring.application.name=notification
server.port=8087

# connection with rabbitmq
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# keys define here that we will be using in the java code.
rabbitmq.exchange.name=order.exchange
rabbitmq.queue.name=order.queue
rabbitmq.routing.key=order.tracking

# Spring Cloud Stream configuration
# Destination is the name of the exchange (order.exchange) from which messages will be received
# and content type is application/json.
spring.cloud.stream.bindings.orderCreatedEventConsumer-in-0.destination=order.exchange
spring.cloud.stream.bindings.orderCreatedEventConsumer-in-0.content-type=application/json

# Function definition (it will be used by the stream).
spring.cloud.function.definition=orderCreatedEventConsumer
spring.cloud.stream.function.definition=orderCreatedEventConsumer