spring.application.name=notification
server.port=8087

# connection with rabbitmq
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# keys define here that we will be using in the java code.
rabbitmq.exchange.name=order.exchange
rabbitmq.queue.name=order.queue
rabbitmq.routing.key=order.tracking