spring.application.name=gateway

server.port=8086

#routing the request to appropriate service using some routing logic. 0 means as this is an array.
# id is the unique identifier given to route.
# uri is the url of the service that the route will forward the request to.
# predicates is the condition which the incoming request must meet to be forwarded to the service.
spring.cloud.gateway.routes[0].id=product-service
spring.cloud.gateway.routes[0].uri=http://localhost:8084
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/products/**

spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=http://localhost:8083
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**

spring.cloud.gateway.routes[2].id=order-service
spring.cloud.gateway.routes[2].uri=http://localhost:8085
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/orders/**
spring.cloud.gateway.routes[2].predicates[1]=Path=/api/cart/**


logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE

management.tracing.sampling.probability=1.0

management.endpoints.web.exposure.include=*
