server.port=8085

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.jpa.show-sql=true
#spring.jpa.generate-ddl-auto=create

spring.datasource.url=jdbc:mysql://localhost:3306/order
# externalizing sensitive config information in the .env file located inside order directory
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database=mysql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# expose all actuator endpoints, including prometheus endpoint which give metrics data in the format compatible with prometheus
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true

# connection with rabbitmq
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# keys define here that we will be using in the java code. Exchange is used to send messages to queue,
# queue is used to store messages, routing key is used to route messages to queue.
rabbitmq.exchange.name=order.exchange
rabbitmq.queue.name=order.queue
rabbitmq.routing.key=order.tracking

# eureka properties
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# so each service will have different log file name
#logging.level.root=INFO
logging.file.name=logs/${spring.application.name}.log

# keep the logs for 7 days
logging.logback.rollingpolicy.max-file-size=5MB
logging.logback.rollingpolicy.max-history=7

#zipkin
# all the request passing will be traced means 100% sampling
management.tracing.sampling.probability=1.0

#circuit breaker
# registerHealthIndicator --> register the circuit breaker with health endpoint of actuator
resilience4j.circuitbreaker.instances.productService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.productService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.productService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.productService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.productService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.productService.failureThreshold=50
resilience4j.circuitbreaker.instances.productService.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.productService.slidingWindowType=count_based
# after 5 api calls with 3 sec gap, the fallback will be called (retry with circuit breaker)
resilience4j.retry.instances.productService.maxAttempts=5
resilience4j.retry.instances.productService.waitDuration=3s

# rate limiting with circuit breaker
resilience4j.ratelimiter.instances.productService.timeout-duration=0
resilience4j.ratelimiter.instances.productService.limit-refresh-period=4s
resilience4j.ratelimiter.instances.productService.limit-for-period=2

# Spring Cloud Stream configuration
# Destination is the name of the exchange (order.exchange) and content type is application/json.
spring.cloud.stream.bindings.createOrder-out-0.destination=order.exchange
spring.cloud.stream.bindings.createOrder-out-0.content-type=application/json

spring.cloud.stream.rabbit.bindings.createOrder-out-0.producer.routing-key-expression="order.tracking"







