spring.application.name=configserver
server.port=8888

# profile is native since we will be storing our configurations files in the local directory,
# other options are git, jdbc etc
spring.profiles.active=native

# our configs will be inside the classpath under resources folder called config. In case of classpath
# based location the config server will not re-read the changes in of any property change in the
# files under config folder, so instead of classpath we have to make use of external file
# searchLocation instead of classpath (spring.cloud.config.server.native.searchLocations=classapath:config)
spring.cloud.config.server.native.searchLocations=file:C:/Users/Salman Asad/Documents/Projects_2026/ecom-microservices/configserver/src/main/resources/config/

# expose all actuator endpoints
management.endpoints.web.exposure.include=*

# connection with rabbitmq so we can trigger bus-refresh
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# eureka properties
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true