spring.application.name=configserver
server.port=8888

# profile is native since we will be storing our configurations files in the local directory,
# other options are git, jdbc etc
spring.profiles.active=native

# our configs will be inside the classpath under resources folder called config
spring.cloud.config.server.native.searchLocations=classpath:/config

# expose all actuator endpoints
management.endpoints.web.exposure.include=*